config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'omniauth_callbacks/vkontakte'
  end

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "books#index"

  resources :books
  resources :users, only: [:show, :edit, :update]
  resources :sections
  resources :lists
  resources :chats

  resources :books do
    member do
      get 'create_booklist'
      get 'create_search'
    end
  end

  concern :commentable do |options|
    resources :comments, options
  end

  resources :books, only: [:create, :destroy] do
    concerns :commentable, commentable_type: 'Book'
  end

  resources :chats, only: [:create, :destroy] do
    concerns :commentable, commentable_type: 'Chat'
  end

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :book_lists, dependent: :destroy
  has_many :books, through: :book_lists, source: :book

  validates :name, presence: true, length: { maximum: 20 }

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def show
    @model = @list
    @books = BookList.where(list: @list).map(&:book)
    @sections = Section.all
    @lists = List.where(user: current_user)
    @chats = Chat.all
    render 'books/index'
  end

  def new
    @list = current_user.lists.build
  end

  def edit
  end

  def create
    @list = current_user.lists.build(list_params)

    if @list.save
      redirect_to root_path, notice: I18n.t('controllers.lists.created')
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to root_path, notice: I18n.t('controllers.lists.updated')
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path, notice: I18n.t('controllers.lists.destroyed')
  end

  private

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:user_id, :name)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%# Паршиал дляотображения формы создания нового списка пользователя %>
<%= form_for(@list) do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: @list} %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
      или <%= link_to 'вернуться', :back %>
    </div>
<% end %>

app/views/lists/_list.html.erb
<div class="buffer-section">
  <a href="#"><%= link_to list.name, list_path(list) %>
  <% if current_user_can_edit?(list) %>
    <%= link_to(fa_icon('edit'), edit_list_path(list)) %>
    <% unless list.books.any? %>
      <%= link_to(
              fa_icon('trash'), list_path(list),
              method: :delete, data: {confirm: t('view.message.sure')}
          ) %>
    <% end %>
  <% end %>
    <span class="badge pull-right badge-list"><%= BookList.where(list: list).map(&:book).count %></span>
  </a>
</div>

app/views/lists/edit.html.erb
<h1>Редактирование списка</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Новый список</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>