config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'omniauth_callbacks/vkontakte'
  end

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "books#index"

  resources :books
  resources :users, only: [:show, :edit, :update]
  resources :sections
  resources :lists
  resources :chats

  resources :books do
    member do
      get 'create_booklist'
      get 'create_search'
    end
  end

  concern :commentable do |options|
    resources :comments, options
  end

  resources :books, only: [:create, :destroy] do
    concerns :commentable, commentable_type: 'Book'
  end

  resources :chats, only: [:create, :destroy] do
    concerns :commentable, commentable_type: 'Chat'
  end

end

app/models/section.rb
class Section < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :name, presence: true, length: { maximum: 35 }
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  def show
    @model = @section
    @books = Book.where(section: @section)
    @sections = Section.all
    @lists = List.where(user: current_user)
    @chats = Chat.all
    render 'books/index'
  end

  def new
    @section = Section.new
  end

  def edit
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to root_path, notice: I18n.t('controllers.sections.created')
    else
      render :new
    end
  end

  def update
    if @section.update(section_params)
      redirect_to @section, notice: I18n.t('controllers.sections.updated')
    else
      render :edit
    end
  end

  def destroy
    @section.destroy
    redirect_to root_path, notice: I18n.t('controllers.sections.destroyed')
  end

  private

  def set_section
    @section = Section.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:name)
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%# Паршиал дляотображения формы создания нового раздела %>
<%= form_for(@section) do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: @section} %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
      или <%= link_to 'вернуться', :back %>
    </div>
<% end %>

app/views/sections/_section.html.erb
<div class="buffer-section">
  <a href="#"><%= link_to section.name, section_path(section) %>
  <% if current_user_is_admin? %>
      <%= link_to(fa_icon('edit'), edit_section_path(section)) %>
      <% if Book.where(section: section) == [] %>
        <%= link_to(
               fa_icon('trash'), section_path(section),
               method: :delete, data: {confirm: t('view.message.sure')}
        ) %>
      <% end %>
  <% end %>
    <span class="badge pull-right badge-section"><%= Book.where(section: section).count %></span>
  </a>
</div>

app/views/sections/edit.html.erb
<h1>Редактирование раздела</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/sections/new.html.erb
<h1>Новый раздел</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>