config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'omniauth_callbacks/vkontakte'
  end

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "books#index"

  resources :books
  resources :users, only: [:show, :edit, :update]
  resources :sections
  resources :lists
  resources :chats

  resources :books do
    member do
      get 'create_booklist'
      get 'create_search'
    end
  end

  concern :commentable do |options|
    resources :comments, options
  end

  resources :books, only: [:create, :destroy] do
    concerns :commentable, commentable_type: 'Book'
  end

  resources :chats, only: [:create, :destroy] do
    concerns :commentable, commentable_type: 'Chat'
  end

end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable

  validates :theme, presence: true, length: {maximum: 100}

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  def show
    @model = @chat
    @new_comment = @chat.comments.build(params[:comment])
  end

  def new
    @chat = current_user.chats.build
  end

  def edit
  end

  def create
    @chat = current_user.chats.build(chat_params)

    if @chat.save
      redirect_to root_path, notice: I18n.t('controllers.chats.created')
    else
      render :new
    end
  end

  def update
    if @chat.update(chat_params)
      redirect_to root_path, notice: I18n.t('controllers.chats.updated')
    else
      render :edit
    end
  end

  def destroy
    @chat.destroy
    redirect_to root_path, notice: I18n.t('controllers.chats.destroyed')
  end

  private

  def set_chat
    @chat = Chat.find(params[:id])
  end

  def chat_params
    params.require(:chat).permit(:user_id, :theme)
  end
end

app/views/chats/_chat.html.erb
<div class="buffer-top-search a_list">
  <a href="#"><%= link_to chat.theme, chat_path(chat) %>
  <% if current_user_can_edit?(chat) %>
    <%= link_to(fa_icon('edit'), edit_chat_path(chat)) %>
    <% unless chat.comments.any? %>
      <%= link_to(
              fa_icon('trash'), chat_path(chat),
              method: :delete, data: {confirm: t('view.message.sure')}
      ) %>
    <% end %>
  <% end %>
    <span class="badge pull-right badge-chat">
      <%= Comment.where(commentable_type: 'Chat', commentable_id: chat).count %></span>
  </a>
</div>

app/views/chats/_form.html.erb
<%# Паршиал дляотображения формы создания новой темы беседы %>
<%= form_for(@chat) do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: @chat} %>

    <div class="form-group">
      <%= f.label :theme %>
      <%= f.text_field :theme, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
      или <%= link_to 'вернуться', :back %>
    </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Редактирование темы</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/chats/new.html.erb
<h1>Новая тема беседы</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/chats/show.html.erb
<div class="container padd0-left">
<div class="row buffer-top">
  <div class="col-md-10">
      <h2><%= @chat.theme %></h2>
  </div>
  <div class="col-md-2">
    <span>Добавил:<%= render partial: 'users/user', object: @chat.user %></span>
  </div>
</div>

<div class="row buffer-top">
<div class="col-md-12">
    <% if user_signed_in? %>
        <%= render partial: 'comments/form',
                   locals: {comment: @new_comment || @chat.comments.build} %>
    <% end %>

    <div class="buffer-both">
      <%= render partial: 'comments/comment',
                 collection: @chat.comments.except(@new_comment) %>
    </div>
</div>
</div>

<div class="buffer-list">
  <%= link_to t('view.btn.backbook'), books_path %>
</div>
</div>