config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'omniauth_callbacks/vkontakte'
  end

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "books#index"

  resources :books
  resources :users, only: [:show, :edit, :update]
  resources :sections
  resources :lists
  resources :chats

  resources :books do
    member do
      get 'create_booklist'
      get 'create_search'
    end
  end

  concern :commentable do |options|
    resources :comments, options
  end

  resources :books, only: [:create, :destroy] do
    concerns :commentable, commentable_type: 'Book'
  end

  resources :chats, only: [:create, :destroy] do
    concerns :commentable, commentable_type: 'Chat'
  end

end

app/models/book.rb
class Book < ApplicationRecord
  include PgSearch
  pg_search_scope :search, against: [:title, :author],
                  using: {tsearch: {dictionary: "russian"}}
  belongs_to :user
  belongs_to :section

  has_many :book_lists, dependent: :destroy
  has_many :lists, through: :book_lists, source: :list
  has_many :comments, as: :commentable

  validates :user, presence: true
  validates :section, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :author, presence: true, length: { maximum: 50 }
  validates :title, uniqueness: true

  mount_uploader :book_url, BookUploader
end

app/controllers/books_controller.rb
require 'book_search'
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_book, only: [:show, :create_booklist, :edit, :update, :destroy]
  include BookSearch

  def index
    if params[:query]
      @books = Book.search(params[:query])
    else
      @books = Book.all
    end
    @model = []
    @sections = Section.all
    @lists = List.where(user: current_user)
    @chats = Chat.all
  end

  def show
    @model = @book
    @new_comment = @book.comments.build(params[:comment])
  end

  def new
    @book = current_user.books.build
  end

  def edit
    @comment_search = 'edit'
  end

  def create
    @book = current_user.books.build(book_params)
    @comment_search = ''

    # поиск обложки в сети при наличии названия книги
    if params[:commit] == 'поиск книги'
       find_books(params)

    # выбрана найденная в сети книга, добавляем в библиотеку
    elsif params[:commit] == 'выбрать' && params[:id_search]
      add_book(params)
      
    # заполнили форму вручную, добавляем книгу
    elsif @book.save
      redirect_to root_path, notice: I18n.t('controllers.books.created')
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: I18n.t('controllers.books.updated')
    else
      render :edit
    end
  end

  def destroy
    if BookList.where(book: @book) == []
      @book.destroy
      redirect_to root_path, notice: I18n.t('controllers.books.destroyed')
    else
      redirect_to book_path(@book), notice: I18n.t('controllers.books.nodelete')
    end
  end


  # добавление книги в список пользователя
  def create_booklist
    # проверка: книга есть в выбранном списке - о чем и сообщаем
    if BookList.where(book: @book, list: List.find(params[:query])).exists?
      redirect_to @book, notice: I18n.t('controllers.books.alreadyadded')

    # проверка: книга есть в одном из списков - переносим в выбранный список
    elsif BookList.where(book: @book, list: List.where(user_id: current_user.id)).exists?
      BookList.where(book: @book, list: List.where(user_id: current_user.id)
                    ).update(list: List.find(params[:query]))
      redirect_to @book, notice: I18n.t('controllers.books.moved')

    # добавляем книгу в список
    else
      BookList.create!(book: @book, list: List.find(params[:query]))
      redirect_to @book, notice: I18n.t('controllers.books.add')
    end
  end

  private

    def find_books(params)
      # проверяем, есть ли уже такая книга, и переходим к найденной книге
        @books = Book.search("#{params[:book][:title]} #{params[:book][:author]}")
        if @books.present?
          redirect_to book_path(@books[0][:id]), notice: 'Такая книга уже есть в нашей библиотеке'
        else
          # поиск книги в сети
          @books_from_net = []
          @books_from_net = BookSearch.search(params[:book][:title],
                                              params[:book][:author]) unless params[:book].key?('book_url')
          @comment_search = 'Книга не найдена' if @books_from_net == []
          render :new
        end
    end


   def add_book(params)
    @book.author = params[:id_author]
      @book.title = params[:id_title]
      @book.description = params[:id_description]
      @book.remote_book_url_url = params[:id_image_url]
      if @book.save
        redirect_to book_path(@book), notice: I18n.t('controllers.books.created')
      else
        render :new
      end
  end


  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :book_url, :description, :section_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="col-md-9 col-md-3">
<div class="row" >
<div class="col-md-12 padd0-left">
<div class="thumbnail thumbnail-list">
  <a href="" target="_blank">
      <%= link_to image_tag(book_img(book)), book_path(book), class: 'img-responsive' %>
  <div class="caption title-gradient">
    <div><%= book.title %></div>
    <%= book.author %>
  </div>
  </a>
</div>
</div>
</div>
</div>

app/views/books/_form.html.erb
<%# Паршиал для отображения формы создания новой книги %>
<%= form_for [@book], html: { multipart: true } do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @book} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :section %>
    <%= f.collection_select(:section_id, Section.all, :id, :name) %>
  </div>

  <% if @comment_search == 'edit' %>
    <div class="form-group">
      <%= f.label :book_url %>
      <p><%= image_tag(@book.book_url.thumb.url) if @book.book_url? %></p>
      <%= f.file_field :book_url %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
      или <%= link_to 'вернуться', :back %>
    </div>
  <% else %>

    <div class="actions buffer-top">
      <%= f.submit 'Создать без обложки', class: 'btn btn-primary' %>
      или <%= link_to 'вернуться', :back %>
      <span class="buffer-left-btn"><%= submit_tag "поиск книги", class: 'btn btn-success' %></span>
    </div>
  <% end %>

  <% if @books_from_net && @books_from_net != [] %>
    <h3>Книга подходит?</h3>
      <% @books_from_net.each_with_index do |book, id_search| %>
        <div class="thumbnail thumbnail-list">
            <%= image_tag(book[:image_url]) %>
          <a href="" target="_blank">
            <%= hidden_field_tag('id_search', id_search) %>
            <%= hidden_field_tag('id_author', book[:author]) %>
            <%= hidden_field_tag('id_title', book[:title]) %>
            <%= hidden_field_tag('id_description', book[:description]) %>
            <%= hidden_field_tag('id_image_url', book[:image_url]) %>
            <div class="caption text-center">
              <%= submit_tag "выбрать", class: 'btn btn-success btn-sm' %>
            </div>
          </a>
        </div>
      <% end %>
  <% else %>
    <p class="buffer-top"> <%= @comment_search unless @comment_search == 'edit' %> </p>
  <% end %>

<% end %>

app/views/books/edit.html.erb
<h1>Редактирование книги</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">

  <div class="col-md-3">
    <div class="row">
      <div class="buffer-both buffer-right">
        <a href="#"><%= link_to 'Все', root_path %>
          <span class="badge pull-right badge-section"><%= Book.count %></span>
        </a>
        <%= render partial: 'sections/section', collection: @sections %>
      </div>
      <% if current_user_is_admin? %>
          <%= link_to 'Создать раздел', new_section_path, class: 'btn btn-success btn-xs' %>
      <% end %>

      <div class="buffer-both buffer-right">
      <% if user_signed_in? %>
          <div class="buffer-list">
            <h4>Мои списки:</h4>
          </div>
          <% if current_user.lists.any? %>
              <%= render partial: 'lists/list', collection: @lists %>
          <% else %>
              <p>Пока нет ни одного списка</p>
          <% end %>
          <div class="buffer-top">
            <%= link_to 'Создать список', new_list_path, class: 'btn btn-success btn-xs' %>
          </div>
      <% end %>
      </div>

      <div class="buffer-both buffer-right">
      <div class="buffer-list">
        <h4>Беседа:</h4>
      </div>
      <% if Chat.any? %>
          <%= render partial: 'chats/chat', collection: @chats %>
      <% else %>
          <p>Пока нет ни одной темы</p>
      <% end %>
      <% if user_signed_in? %>
          <div class="buffer-top">
            <%= link_to 'Создать тему беседы', new_chat_path, class: 'btn btn-success btn-xs' %>
          </div>
      <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <div class="row">
    <% if @model == [] %>
      <h4 class="text-left">Раздел библиотеки: Все</h4>
    <% else %>
      <h4 class="text-left">Раздел библиотеки: <%= @model.name %></h4>
    <% end %>
    </div>

   <div class="row">
     <% unless @books && @books == []  %>
       <%# Рендерим массив книг, каждый в паршиале 'books/book' %>
       <%= render partial: 'books/book', collection: @books %>
     <% else %>
       <p class="buffer-top">Книги отсутствуют ... Добавляйте! </p>
     <% end %>
   </div>
  </div>


</div>
</div>

app/views/books/new.html.erb
<h1>Новая книга</h1>

<div class="row">
  <div class="col-md-6 buffer-section">
    <p>(для поиска книги в сети введите название книги(можно не полностью)
      и фамилию автора, нажмите <strong>поиск книги</strong>)</p>
    <%= render 'form' %>
  </div>
</div>

app/views/books/show.html.erb
<div class="container padd0-left">
<div class="row">
  <div class="col-md-4 buffer-top">
   <div class="thumbnail thumbnail-book">
       <%= image_tag(book_img(@book)) %>
   </div>

   <% if current_user_can_edit?(@book) || current_user_is_admin? %>
     <div class="buffer-top">
       <%= link_to t('view.btn.change'), edit_book_path(@book),
                      class: 'btn btn-primary' %>
       <%= link_to t('view.btn.delete'), book_path(@book),
                      method: :delete, data: { confirm: t('view.message.sure') }, class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-6 padd0-left">
      <h2> <%= @book.title %> </h2>
      <h3> <%= @book.author %> </h3>
      <span class="buffer-top">Раздел библиотеки: <%= @book.section.name %> </span>
      <p class="buffer-top p_book"> <%= @book.description %> </p>
  </div>
  <div class="col-md-2 buffer-top">
    <span>Добавил:<%= render partial: 'users/user', object: @book.user %></span>
  </div>
</div>

<div class="row buffer-top">
  <div class="col-md-4">
    <div class="buffer-add">
      <% if current_user_can_add_book? %>
        <h4>Добавить книгу в мой список</h4>
        <%= form_tag create_booklist_book_path(@book), :method => :get do %>
          <%= render partial: 'partials/form_errors', locals: {model: @book} %>
          <p class="buffer-top">
            <%= select_tag :query, options_for_select(current_user.lists.collect{ |u| [u.name, u.id] }, params[:query])%>
            <%= submit_tag "Добавить", class: 'btn btn-primary btn-sm' %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-md-8">
    <div class="row">
      <% if user_signed_in? %>
          <%= render partial: 'comments/form',
                     locals: {comment: @new_comment || @book.comments.build} %>
      <% end %>

      <div class="buffer-both">
        <%= render partial: 'comments/comment',
                   collection: @book.comments.except(@new_comment) %>
      </div>
    </div>
  </div>
</div>

<div class="buffer-list">
<%= link_to t('view.btn.backbook'), books_path %>
</div>
</div>